
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

RUN apt-get -y update && \
    apt-get -y install openssh-server python3-pip && \
    mkdir -p /root/.ssh && \
    echo 'X11UseLocalhost no' >> /etc/ssh/sshd_config

RUN apt-get -y install tmux git x11-apps vim

COPY requirements.txt /tmp
RUN echo 'alias python=python3' >> /root/.bashrc
RUN echo 'alias pip=pip3' >> /root/.bashrc
RUN pip3 install --upgrade pip
RUN pip3 install -r /tmp/requirements.txt

EXPOSE 22
VOLUME /workspace

ENTRYPOINT service ssh restart && bash